In [1]:
import pandas as pd

In [2]:
plant_product_weekly_demand = pd.read_csv(r'data/processed/plant_product_weekly_demand.csv')

In [3]:
print("Plants:", plant_product_weekly_demand["Plant_ID"].nunique())
print("Products:", plant_product_weekly_demand["Product Card Id"].nunique())
print("Weeks:", plant_product_weekly_demand["Order_Date"].nunique())

Plants: 3
Products: 118
Weeks: 162

In [5]:
top_product_driver = pd.read_csv(r'data/processed/top_product_driver_weekly.csv')

In [6]:
top_product_driver.head()

,Plant_ID,Product Card Id,Product Name,Order_Date,Weekly_Demand,Demand_Rank,Demand_Last_Week,Demand_Change,Demand_Growth,Plant_Weekly_Demand,Demand_Contribution,Demand_Contribution_Pct,Cumulative_Contribution
0,P1,365,Perfect Fitness Perfect Rip Deck,2015-01-04,306,1.0,NaN,NaN,NaN,567,0.539683,53.97,0.539683
1,P1,191,Nike Men's Free 5.0+ Running Shoe,2015-01-04,160,2.0,NaN,NaN,NaN,567,0.282187,28.22,0.821869
2,P1,403,Nike Men's CJ Elite 2 TD Football Cleat,2015-01-04,77,3.0,NaN,NaN,NaN,567,0.135802,13.58,0.957672
3,P1,276,Under Armour Women's Ignite Slide,2015-01-04,10,4.0,NaN,NaN,NaN,567,0.017637,1.76,0.975309
4,P1,172,Nike Women's Tempo Shorts,2015-01-04,6,5.0,NaN,NaN,NaN,567,0.010582,1.06,0.985891

In [7]:
top_product_driver.columns

Index(['Plant_ID', 'Product Card Id', 'Product Name', 'Order_Date',
       'Weekly_Demand', 'Demand_Rank', 'Demand_Last_Week', 'Demand_Change',
       'Demand_Growth', 'Plant_Weekly_Demand', 'Demand_Contribution',
       'Demand_Contribution_Pct', 'Cumulative_Contribution'],
      dtype='object')

In [2]:
inventory_risk_weekly = pd.read_csv(r'data/processed/inventory_risk_weekly.csv')

In [3]:
inventory_risk_weekly.columns

Index(['Plant_ID', 'Product Card Id', 'Product Name', 'Order_Date',
       'Weekly_Demand', 'Initial_Inventory', 'Target_Coverage_Days',
       'Average_Daily_Demand', 'Review_Cycle', 'Beginning_Inventory',
       'Ending_Inventory', 'Replenishment_Qty', 'Target_Inventory',
       'Safety_Stock_Days', 'Inventory_On_Hand', 'DOI', 'Inventory_Status',
       'Reorder_Risk', 'ABC_Class', 'Inventory_Utilization',
       'Inventory_Alert'],
      dtype='object')

In [4]:
inventory_risk_weekly['Inventory_Alert']

0       0
1       0
2       0
3       0
4       0
       ..
7603    0
7604    0
7605    0
7606    0
7607    0
Name: Inventory_Alert, Length: 7608, dtype: int64

In [5]:
inventory_risk_weekly[
    ['Reorder_Risk']
].describe()

       Reorder_Risk
count          7608
unique            2
top              No
freq           4356

In [2]:
service_risk = pd.read_csv(r'data/processed/service_risk_weekly.csv')

In [3]:
service_risk.columns

Index(['Plant_ID', 'Product Card Id', 'Product Name', 'Order_Date',
       'Weekly_Demand', 'Initial_Inventory', 'Target_Coverage_Days',
       'Average_Daily_Demand', 'Review_Cycle', 'Beginning_Inventory',
       'Ending_Inventory', 'Replenishment_Qty', 'Target_Inventory',
       'Safety_Stock_Days', 'Inventory_On_Hand', 'DOI', 'Inventory_Status',
       'Reorder_Risk', 'ABC_Class', 'Inventory_Utilization', 'Inventory_Alert',
       'Capacity_Status', 'Service_Risk', 'Service_Alert',
       'Service_Risk_Score', 'Risk_Driver'],
      dtype='object')

In [8]:
service_risk

,Plant_ID,Product Card Id,Product Name,Order_Date,Weekly_Demand,Initial_Inventory,Target_Coverage_Days,Average_Daily_Demand,Review_Cycle,Beginning_Inventory,...,Inventory_Status,Reorder_Risk,ABC_Class,Inventory_Utilization,Inventory_Alert,Capacity_Status,Service_Risk,Service_Alert,Service_Risk_Score,Risk_Driver
0,P2,19,Nike Men's Fingertrap Max Training Shoe,2017-04-30,2,48,21,0.457143,0,48.0,...,Normal,No,C,4.600000,0,Normal,Low,0,1,NaN
1,P2,19,Nike Men's Fingertrap Max Training Shoe,2017-05-07,3,48,21,0.457143,0,46.0,...,Normal,No,C,4.300000,0,Normal,Low,0,1,NaN
2,P2,19,Nike Men's Fingertrap Max Training Shoe,2017-05-14,1,48,21,0.457143,0,43.0,...,Normal,No,C,4.200000,0,Normal,Low,0,1,NaN
3,P2,19,Nike Men's Fingertrap Max Training Shoe,2017-05-21,3,48,21,0.457143,0,42.0,...,Normal,No,C,3.900000,0,Normal,Low,0,1,NaN
4,P2,19,Nike Men's Fingertrap Max Training Shoe,2017-05-28,6,48,21,0.457143,1,39.0,...,Normal,No,C,3.300000,0,Normal,Low,0,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7603,P1,1363,Summer dresses,2018-01-07,0,1219,21,11.607143,0,947.0,...,Normal,No,C,3.881148,0,Normal,Low,0,1,NaN
7604,P1,1363,Summer dresses,2018-01-14,0,1219,21,11.607143,1,947.0,...,Normal,No,C,3.881148,0,Normal,Low,0,1,NaN
7605,P1,1363,Summer dresses,2018-01-21,0,1219,21,11.607143,1,947.0,...,Normal,No,C,3.881148,0,Normal,Low,0,1,NaN
7606,P1,1363,Summer dresses,2018-01-28,176,1219,21,11.607143,1,947.0,...,Normal,No,C,3.159836,0,Normal,Low,0,1,NaN
7607,P1,1363,Summer dresses,2018-02-04,202,1219,21,11.607143,1,771.0,...,Normal,No,C,2.331967,0,Normal,Low,0,1,NaN